version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing Node.js dependencies...
      - npm install
  pre_build:
    commands:
      - echo Installing AWS CLI...

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
